# frozen_string_literal: true

namespace :decidim_meetings do
  desc <<~DESC.squish
    Import meetings into a meetings component from a JSON file generated by the admin meetings export.
    Pass the file path and the target component id as task arguments, or set ENV['FILE'] and ENV['COMPONENT_ID'].
    Set ENV['ADMIN_USER_ID'] (or ENV['ADMIN_EMAIL']) to the user the created versions are attributed to.
    Default DRY_RUN=true; set ENV['DRY_RUN']=false to write.
    Optional ENV['PUBLISH'] (none|silent|notify, default none), ENV['ON_DUPLICATE'] (skip|create, default skip),
    ENV['LIMIT'] and ENV['SOURCE_IDS'].
  DESC
  task :import_from_json, [:file, :component_id] => :environment do |_task, args|
    file = args[:file].presence || ENV.fetch("FILE", nil)
    component_id = args[:component_id].presence || ENV.fetch("COMPONENT_ID", nil)

    usage = "Example: bin/rails \"decidim_meetings:import_from_json[tmp/meetings.json,123]\" ADMIN_USER_ID=1"
    abort "Missing arguments. #{usage}" if file.blank? || component_id.blank?

    component = Decidim::Component.find_by(id: component_id)
    abort "Component #{component_id} not found." unless component

    user = if ENV["ADMIN_USER_ID"].present?
             Decidim::User.find_by(id: ENV.fetch("ADMIN_USER_ID"), organization: component.organization)
           elsif ENV["ADMIN_EMAIL"].present?
             Decidim::User.find_by(email: ENV.fetch("ADMIN_EMAIL"), organization: component.organization)
           end
    abort "Missing or unknown user. Set ADMIN_USER_ID or ADMIN_EMAIL to an admin of #{component.organization.host}." unless user
    puts "Warning: #{user.email} is not an admin of #{component.organization.host}." unless user.admin?

    importer_kwargs = {
      path: file,
      component:,
      current_user: user,
      dry_run: ENV["DRY_RUN"] != "false",
      publish: ENV["PUBLISH"].presence || "none",
      on_duplicate: ENV["ON_DUPLICATE"].presence || "skip"
    }
    importer_kwargs[:limit] = Integer(ENV["LIMIT"]) if ENV["LIMIT"].present?
    importer_kwargs[:source_ids] = ENV["SOURCE_IDS"].split(",") if ENV["SOURCE_IDS"].present?

    begin
      importer = Decidim::Meetings::Import::JsonMeetingsImporter.new(**importer_kwargs)

      puts "Importing #{importer.rows.size} meetings from #{file} into component #{component.id} " \
           "(#{component.participatory_space.class.name} ##{component.participatory_space.id}) " \
           "as #{user.email} (dry_run=#{importer.dry_run?}, publish=#{importer.publish})"
    rescue Decidim::Meetings::Import::JsonMeetingsImporter::ImportError => e
      abort e.message
    end

    results = importer.call
    results.each { |result| puts result }

    counts = results.group_by(&:status).transform_values(&:size).map { |status, count| "#{status}=#{count}" }
    puts "\nTotal: #{results.size} (#{counts.join(", ")}, dry_run=#{importer.dry_run?})"
    puts "Nothing was written. Re-run with DRY_RUN=false to import." if importer.dry_run?
  end
end
