inherit_from:
  - https://raw.githubusercontent.com/decidim/decidim/release/0.29-stable/.rubocop.yml

AllCops:
  Exclude:
    - "spec/decidim_dummy_app*/**/*"
    - "decidim-age_action_authorization/spec/decidim_dummy_app*/**/*"
    - "decidim-census/spec/decidim_dummy_app*/**/*"
    - "decidim-diba_census_api/spec/decidim_dummy_app*/**/*"
    - "decidim-ldap/spec/decidim_dummy_app*/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "**/node_modules/**/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "vendor/**/*"
    - "**/vendor/**/*"
