# frozen_string_literal: true

source "https://rubygems.org"

# git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in decidim-age_action_authorization.gemspec
gemspec

group :development, :test do
  gem "bootsnap"
  gem "decidim", ">= 0.27", { git: "https://github.com/CodiTramuntana/decidim.git", branch: "release/0.27-stable" }.freeze
  gem "decidim-ldap", path: "../decidim-ldap"
  gem "listen"
  gem "pry-rails"
end
