# frozen_string_literal: true

source "https://rubygems.org"

# git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in decidim-age_action_authorization.gemspec
gemspec

group :development, :test do
  gem "bootsnap"
  gem "decidim", ">= 0.29", { git: "https://github.com/decidim/decidim.git", branch: "release/0.29-stable" }.freeze
  gem "letter_opener_web"
  gem "decidim-ldap", path: "../decidim-ldap"
  gem "spring", "~> 4.2.1"
  gem "listen"
  gem "pry-rails"
end
