# frozen_string_literal: true

require "json"

module Decidim
  module Meetings
    module Import
      # Creates meetings into a target meetings component out of a JSON file
      # generated by the admin meetings export.
      #
      # The importable fields are the ones a Decidim 0.28 export carries: title,
      # description, location, address and the start and end times. The rest of
      # that export is either a derived value that cannot be written back
      # (counts, url, reference, attachments, linked resources, author) or a
      # field its serializer does not include at all (coordinates, meeting type,
      # categories and scopes, registrations, closing report), so every imported
      # meeting is created as an official in person meeting with the defaults a
      # new meeting gets from the admin panel. Whatever a newer export adds is
      # ignored.
      class JsonMeetingsImporter
        class ImportError < StandardError; end

        PUBLISH_MODES = %w(none silent notify).freeze
        DUPLICATE_MODES = %w(skip create).freeze

        # None of these are part of the export and the admin form always submits
        # a value for them, so imported meetings get the same values a meeting
        # created from the admin panel would get.
        DEFAULT_ATTRIBUTES = {
          type_of_meeting: "in_person",
          registration_type: "registration_disabled",
          private_meeting: false,
          transparent: false,
          iframe_embed_type: "none",
          iframe_access_level: "all"
        }.freeze

        Result = Struct.new(:index, :source_id, :status, :meeting_id, :messages, keyword_init: true) do
          def to_s
            [
              "row=#{index}",
              "source_id=#{source_id || "-"}",
              "status=#{status}",
              ("meeting_id=#{meeting_id}" if meeting_id),
              (messages.join(" | ") if messages.present?)
            ].compact.join(" ")
          end
        end

        attr_reader :path, :component, :current_user, :publish, :on_duplicate, :limit, :source_ids

        # path         - String path to the exported JSON file.
        # component    - The target Decidim::Component (meetings manifest).
        # current_user - The Decidim::User the created meetings are attributed to.
        # dry_run      - When true (default) nothing is written: rows are only
        #                run through the admin form validations.
        # publish      - "none" (default) leaves the meetings unpublished,
        #                "silent" publishes them without notifying anybody,
        #                "notify" publishes them through the admin command, which
        #                notifies the space followers on every meeting. Rows
        #                exported as unpublished are never published.
        # on_duplicate - "skip" (default) ignores rows whose title and start time
        #                already exist in the target component, "create" imports
        #                them anyway.
        # limit        - Imports at most this number of rows.
        # source_ids   - Imports only the rows with these exported ids.
        # rubocop:disable Metrics/ParameterLists
        def initialize(path:, component:, current_user:, dry_run: true, publish: "none",
                       on_duplicate: "skip", limit: nil, source_ids: nil)
          @path = path
          @component = component
          @current_user = current_user
          @dry_run = dry_run
          @publish = publish.to_s
          @on_duplicate = on_duplicate.to_s
          @limit = limit
          @source_ids = Array(source_ids).map(&:to_i).presence

          validate_arguments!
        end
        # rubocop:enable Metrics/ParameterLists

        def dry_run? = @dry_run

        # Returns an Array of Result, one per imported row.
        def call
          rows.each_with_index.map { |row, index| process(row, index) }
        end

        def rows
          @rows ||= begin
            data = ::JSON.parse(File.read(path))
            data = [data] if data.is_a?(Hash)
            raise ImportError, "#{path} does not contain a JSON array of meetings" unless data.is_a?(Array)

            data = data.map do |row|
              raise ImportError, "every element of #{path} must be a JSON object" unless row.is_a?(Hash)

              row.with_indifferent_access
            end
            data = data.select { |row| source_ids.include?(row[:id].to_i) } if source_ids
            limit ? data.first(limit) : data
          end
        end

        def organization = @organization ||= component.organization

        private

        def validate_arguments!
          raise ImportError, "#{path} does not exist" unless File.exist?(path)
          raise ImportError, "component #{component.id} is not a meetings component" unless component.manifest_name == "meetings"
          raise ImportError, "PUBLISH must be one of #{PUBLISH_MODES.join(", ")}" unless PUBLISH_MODES.include?(publish)
          raise ImportError, "ON_DUPLICATE must be one of #{DUPLICATE_MODES.join(", ")}" unless DUPLICATE_MODES.include?(on_duplicate)
          raise ImportError, "user #{current_user.id} does not belong to #{organization.host}" unless current_user.organization == organization
        end

        def process(row, index)
          messages = []
          existing = duplicate_for(row)
          return result(row, index, :skipped, messages: ["already present as meeting ##{existing.id}"]) if existing && on_duplicate == "skip"

          form = build_meeting_form(row, messages)
          return result(row, index, :invalid, messages: messages + error_messages(form, "meeting")) if form.invalid?
          return result(row, index, :would_import, messages:) if dry_run?

          meeting = apply!(row, form)
          result(row, index, :imported, meeting_id: meeting.id, messages:)
        rescue StandardError => e
          result(row, index, :error, messages: messages + ["#{e.class}: #{e.message}"])
        end

        def apply!(row, form)
          meeting = nil

          ActiveRecord::Base.transaction(requires_new: true) do
            meeting = create_meeting!(form)
            publish_meeting!(meeting) if publish_row?(row)
          end

          meeting
        end

        def create_meeting!(form)
          meeting = nil

          Decidim::Meetings::Admin::CreateMeeting.call(form) do
            on(:ok) { |resource| meeting = resource }
            on(:invalid) { raise ImportError, "meeting could not be created: #{error_messages(form, "meeting").join(" | ")}" }
          end

          meeting
        end

        # The export tells whether the meeting was published in the source
        # component: the ones that were not are imported as drafts as well.
        def publish_row?(row)
          return false if publish == "none"

          row[:published].nil? || row[:published].present?
        end

        def publish_meeting!(meeting)
          return silently_publish!(meeting) if publish == "silent"

          Decidim::Meetings::Admin::PublishMeeting.call(meeting, current_user) do
            on(:invalid) { raise ImportError, "meeting could not be published" }
          end
        end

        def silently_publish!(meeting)
          Decidim.traceability.perform_action!(:publish, meeting, current_user, visibility: "all") do
            meeting.publish!
            meeting
          end
        end

        def build_meeting_form(row, messages)
          Decidim::Meetings::Admin::MeetingForm.from_params(meeting_params(row, messages)).with_context(form_context)
        end

        def form_context
          {
            current_organization: organization,
            current_component: component,
            current_participatory_space: component.participatory_space,
            current_user:
          }
        end

        def meeting_params(row, messages)
          DEFAULT_ATTRIBUTES
            .merge(
              start_time: row[:start_time],
              end_time: row[:end_time],
              address: row[:address]
            ).compact
            .merge(translated_params(:title, row[:title], messages))
            .merge(translated_params(:description, row[:description], messages))
            .merge(translated_params(:location, row[:location], messages))
        end

        # The form assigns each locale on its own so that every value goes
        # through the form attribute type (ie. the rich text sanitizer).
        def translated_params(name, value, messages)
          translated_hash(value, messages).transform_keys do |locale|
            :"#{name}_#{locale.gsub("-", "__")}"
          end
        end

        def translated_hash(value, messages = [])
          return {} if value.blank?

          organization_locale = organization.default_locale.to_s
          return { organization_locale => value } if value.is_a?(String)

          available = value.to_h.stringify_keys.except("machine_translations").compact_blank
          available[organization_locale] = available.values.find(&:present?) if available.keys.exclude?(organization_locale)

          dropped = available.keys - importable_locales
          messages << "dropped unavailable locales: #{dropped.join(", ")}" if dropped.any?

          available.slice(*importable_locales)
        end

        def importable_locales
          @importable_locales ||= organization.available_locales.map(&:to_s) & Decidim.available_locales.map(&:to_s)
        end

        def duplicate_for(row)
          title = translated_hash(row[:title])[organization.default_locale.to_s]
          start_time = parse_time(row[:start_time])
          return if title.blank? || start_time.blank?

          Meeting.where(component:)
                 .where("title->>? = ?", organization.default_locale.to_s, title)
                 .find_by(start_time:)
        end

        def parse_time(value)
          Time.zone.parse(value.to_s)
        rescue ArgumentError
          nil
        end

        def error_messages(form, prefix)
          return [] if form.blank?

          form.errors.map { |error| "#{prefix}: #{error.full_message}" }
        end

        def result(row, index, status, meeting_id: nil, messages: [])
          Result.new(index:, source_id: row[:id], status:, meeting_id:, messages:)
        end
      end
    end
  end
end
