decidim_open_data_export:
  cron: '0 4 * * * Europe/Madrid'
  class: 'OpenDataExport'
decidim_metrics_all:
  cron: '0 2 * * * Europe/Madrid'
  class: 'Metrics'
decidim_initiatives_check_validating:
  cron: '0 1 * * * Europe/Madrid'
  class: 'DecidimInitiativesCheckValidating'
decidim_initiatives_check_published:
  cron: '0 3 * * * Europe/Madrid'
  class: 'DecidimInitiativesCheckPublished'
decidim_initiatives_notify_progress:
  cron: '0 5 * * * Europe/Madrid'
  class: 'DecidimInitiativesNotifyProgress'
