name: "[CI] app"

on:
  push:
    branches:
      - master
      - release/*
      - "*-stable"
  pull_request:

env:
  RUBY_VERSION: 3.1.2
  NODE_VERSION: 18.17.1

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Recover Ruby dependency cache
        uses: actions/cache@v4
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-app-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-app-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-app-rubydeps-

      - name: Set bundle local config vendor/bundle path
        run: bundle config set --local path 'vendor/bundle'

      - name: Install Ruby deps
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: bundle install --jobs 4 --retry 3

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm install
      - run: bundle exec rake db:test:prepare
        name: Setup database
      - name: Run RSpec
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: CI=1 RAILS_ENV=test bundle exec rspec --backtrace
