name: "[CI] app"

on:
  push:
    branches:
      - master
      - release/*
      - "*-stable"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version-file: .ruby-version
          bundler-cache: true

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - run: npm install

      - run: sudo apt update && sudo apt install -y imagemagick

      - run: bundle exec rake db:test:prepare
        name: Setup database

      - name: Run RSpec
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: CI=1 RAILS_ENV=test bundle exec rspec --backtrace
