name: "[CI] Diba Census API"

on:
  push:
    branches:
      - master
      - release/*
      - "*-stable"
  pull_request:

jobs:
  test-report:
    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/decidim-diba_census_api/Gemfile
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost

    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version-file: .ruby-version
          bundler-cache: true

      - name: Generate diba_census_api test_app
        run: |
          cd decidim-diba_census_api
          bundle exec rake test_app
          cd spec/decidim_dummy_app/
          bundle exec rails decidim_diba_census_api:install:migrations
          RAILS_ENV=test bundle exec rails db:migrate

      - name: Run RSpec
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: |
            cd decidim-diba_census_api
            CI=1 RAILS_ENV=test bundle exec rspec --backtrace
