name: "[CI] Lint code"

on:
  push:
    branches:
      - master
      - release/*
      - "*-stable"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version-file: .ruby-version
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop -P

      # erb-lint < 0.0.33 raises a NameError but can't upgrade due to gem dependency incompatibilities
      # These incompatibilities are already solved in decidim v0.24 but it still has to be released
      # Uncomment the following lines after the upgrade
      #
      # - name: Erb linter
      #   run: bundle exec erblint app/views/**/*.erb
